default:
  crowd_username: <%= ENV['CAPTIONCAST_CROWD_USERNAME'] %>
  crowd_password: <%= ENV['CAPTIONCAST_CROWD_PASSWORD'] %>
  crowd_base_url: <%= ENV['CAPTIONCAST_CROWD_BASE_URL'] %>

production:
  <<: *default;

development:
  <<: *default;

test:
  <<: *default;